"""init schema

Revision ID: 1ecfa417d02a
Revises: 
Create Date: 2026-06-21 12:23:34.831828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecfa417d02a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex_at_birth', sa.String(length=64), nullable=True),
    sa.Column('consent_accepted', sa.Boolean(), nullable=False),
    sa.Column('consent_accepted_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_cognito_sub'), 'patients', ['cognito_sub'], unique=True)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('actor_cognito_sub', sa.String(length=256), nullable=False),
    sa.Column('action', sa.Enum('read', 'write', 'delete', name='audit_action'), nullable=False),
    sa.Column('resource', sa.Enum('onboarding', 'labs', 'suggestions', 'recipes', 'rejections', name='audit_resource'), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('event_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_event_at'), 'audit_log_entries', ['event_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_patient_id'), 'audit_log_entries', ['patient_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('hba1c', 'fasting_glucose', 'total_cholesterol', 'triglycerides', name='lab_kind'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('unit', sa.Enum('percent', 'mg_per_dl', name='lab_unit'), nullable=False),
    sa.Column('sample_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.create_table('nutritional_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('diabetes_type', sa.Text(), nullable=True),
    sa.Column('diagnosis_date', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutritional_profiles_patient_id'), 'nutritional_profiles', ['patient_id'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('clinical_context_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_patient_id'), 'recipes', ['patient_id'], unique=False)
    op.create_table('rejected_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_normalized', sa.Text(), nullable=False),
    sa.Column('ingredient_display', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejected_ingredients_patient_id'), 'rejected_ingredients', ['patient_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('source_ingredient', sa.Text(), nullable=False),
    sa.Column('clinical_context_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_patient_id'), 'suggestions', ['patient_id'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nutritional_profile_id', sa.Uuid(), nullable=False),
    sa.Column('substance', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nutritional_profile_id'], ['nutritional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_nutritional_profile_id'), 'allergies', ['nutritional_profile_id'], unique=False)
    op.create_table('dietary_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nutritional_profile_id', sa.Uuid(), nullable=False),
    sa.Column('preference', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nutritional_profile_id'], ['nutritional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dietary_preferences_nutritional_profile_id'), 'dietary_preferences', ['nutritional_profile_id'], unique=False)
    op.create_table('intolerances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nutritional_profile_id', sa.Uuid(), nullable=False),
    sa.Column('substance', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nutritional_profile_id'], ['nutritional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intolerances_nutritional_profile_id'), 'intolerances', ['nutritional_profile_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nutritional_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dosage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nutritional_profile_id'], ['nutritional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_nutritional_profile_id'), 'medications', ['nutritional_profile_id'], unique=False)
    op.create_table('suggestion_alternatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suggestion_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank BETWEEN 1 AND 4', name='ck_suggestion_alternatives_rank'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_alternatives_suggestion_id'), 'suggestion_alternatives', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_alternatives_suggestion_id'), table_name='suggestion_alternatives')
    op.drop_table('suggestion_alternatives')
    op.drop_index(op.f('ix_medications_nutritional_profile_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_intolerances_nutritional_profile_id'), table_name='intolerances')
    op.drop_table('intolerances')
    op.drop_index(op.f('ix_dietary_preferences_nutritional_profile_id'), table_name='dietary_preferences')
    op.drop_table('dietary_preferences')
    op.drop_index(op.f('ix_allergies_nutritional_profile_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_suggestions_patient_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_rejected_ingredients_patient_id'), table_name='rejected_ingredients')
    op.drop_table('rejected_ingredients')
    op.drop_index(op.f('ix_recipes_patient_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_nutritional_profiles_patient_id'), table_name='nutritional_profiles')
    op.drop_table('nutritional_profiles')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_audit_log_entries_patient_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_event_at'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_patients_cognito_sub'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
